"""Группировка типов организаций (10 основных категорий)."""

from __future__ import annotations

EVENT_AGENCY_GROUP = "Ивент-агентства и продакшн"

_RULES: list[tuple[str, tuple[str, ...]]] = [
    (
        "Лофты и event-площадки",
        (
            "лофт",
            "loft",
            "ивент-спейс",
            "event space",
            "event venue",
            "rooftop venue",
            "площадка",
            "панorama",
            "панорам",
            "смотровая",
            "верanda",
            "веранда",
            "пространство",
            "90floor",
            "floor \\",
            "loft /",
            "коломенской",
            "пингviloft",
            "пингвилoft",
            "графит",
            "flora \\",
            "izumrud \\",
            "mexico \\",
            "ocean vibe",
            "tropicana",
            "vision \\",
            "wild west",
            "x13 \\",
            '55" жк',
            "парижская квартира",
            "dinamo",
            "динамо",
        ),
    ),
    (
        EVENT_AGENCY_GROUP,
        (
            "ивент агентство",
            "event-агентство",
            "event-агент",
            "event agency",
            "event / creative",
            "event / marketing",
            "event / communications",
            "event / pr",
            "event / promo",
            "event / multimedia",
            "event production",
            "event operator",
            "event-оператор",
            "event department",
            "event ecosystem",
            "event-серия",
            "wedding",
            "свадебн",
            "pr-агентство",
            "pr /",
            "коммуникационное",
            "creative agency",
            "creative / event",
            "creative / multimedia",
            "креативное агентство",
            "marketing / event",
            "experiential",
            "matchmaking",
            "rooftop event agency",
            "концертное агентство",
            "фестивальный организатор",
            "корпоративная event",
            "государственная event",
            "multimedia production",
            "продакшн",
            "production studio",
            "photo studio",
        ),
    ),
    (
        "Отели и проживание",
        ("отель", "hotel", "resort", "spa-отель", "апарт-отель", "гостиничная", "дизайн-отель"),
    ),
    (
        "Рестораны и гастро",
        ("ресторан", "бар", "food", "гастро", "кофе", "kitchen", "cafe", "quick", "питания"),
    ),
    (
        "Маркетинг и реклама",
        (
            "медиаагентство",
            "медиа-агентство",
            "медиабаинг",
            "digital-агентство",
            "digital marketing",
            "digital / creative",
            "adtech",
            "martech",
            "брендинговое",
            "рекламный холдинг",
            "outdoor media",
            "media monitoring",
        ),
    ),
    (
        "Медиа и контент",
        (
            "медиахолдинг",
            "телеканал",
            "радиостанция",
            "видеоплатформа",
            "lifestyle-медиа",
            "медиа /",
            "медиакомпания",
            "медиагруппа",
            "медиаподразделение",
            "издательск",
            "киностудия",
            "кинокомпания",
            "онлайн-кинотеатр",
            "online cinema",
            "entertainment platform",
            "entertainment company",
            "музыкальный",
            "booking",
            "лейбл",
            "журнал",
            "tech-медиа",
            "fashion-меди",
            "бизнес-медиа",
            "it-медиа",
            "digital media",
            "digital-медиа",
            "онлайн-медиа",
            "event/media",
            "спортивное медиа",
            "билетный сервис",
            "streaming",
        ),
    ),
    (
        "Культура, музеи, фестивали",
        (
            "музей",
            "культурн",
            "арт-",
            "art ",
            "галере",
            "ярмарка",
            "планетарий",
            "океанариум",
            "кинофестиваль",
            "фестиваль",
            "концертный зал",
            "концертная площадка",
            "концертный оператор",
            "кинотеатр",
            "театр",
            "урбанистический форум",
            "street culture",
        ),
    ),
    (
        "Спорт, wellness, outdoor",
        (
            "fitness",
            "wellness",
            "гольф",
            "конный",
            "padel",
            "pade",
            "sport",
            "спортив",
            "фитнес",
            "pilates",
            "спортивная арена",
            "спортивный маркетинг",
        ),
    ),
    (
        "Комьюнити и кластеры",
        (
            "комьюнити",
            "community",
            "кластер",
            "бизнес-клуб",
            "business club",
            "private club",
            "private / business",
            "ассоциация",
            "club project",
            "образовательное community",
            "travel community",
            "product management community",
            "marketplace",
            "международный клуб",
            "бизнес-школа",
            "университет",
            "музыкальный вуз",
        ),
    ),
    (
        "Корпорации и финансы",
        (
            "организация",
            "банк",
            "страхов",
            "нефт",
            "металлург",
            "промышлен",
            "девелопер",
            "retail",
            "it-компания",
            "it /",
            "it community",
            "fmcg",
            "энергет",
            "автомоб",
            "логистик",
            "авиакомпания",
            "телеком",
            "cloud",
            "cybersecurity",
            "enterprise software",
            "химическ",
            "агро",
            "почтов",
            "государственн",
            "инвестицион",
            "управляющ",
            "биржа",
            "венчур",
            "табач",
            "судоход",
            "автопроизвод",
            "двигателестро",
            "нефтехим",
            "нефетрейдинг",
            "атомн",
            "e-commerce",
            "ювелир",
            "fintech",
            "hr tech",
            "производитель напитков",
            "компания /",
            "технологическ",
        ),
    ),
]


def classify(org_type: str) -> str:
    t = org_type.lower().strip()
    if not t or t == "n/a":
        return "Корпорации и финансы"
    for group, keys in _RULES:
        if any(k in t for k in keys):
            return group
    return "Корпорации и финансы"


def is_event_agency(org_type: str) -> bool:
    return classify(org_type) == EVENT_AGENCY_GROUP
